# Copyright (c) 2022 Battelle Energy Alliance, LLC.  All rights reserved.

name: "${PCAP_NODE_NAME:malcolm}"

#================================ Modules ======================================
filebeat.modules:
- module: nginx
  access:
    enabled: true
    var.paths: ["${FILEBEAT_NGINX_LOG_PATH:/data/nginx}/access.log*"]
  error:
    enabled: true
    var.paths: ["${FILEBEAT_NGINX_LOG_PATH:/data/nginx}/error.log*"]

#================================ Outputs ======================================

#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
  enabled: true
  hosts: ["opensearch:9200"]
  indices:
    - index: "filebeat-%{[agent.version]}-nginx-%{+yyyy.MM.dd}"
      when.equals:
        event.module: "nginx"

setup.template.enabled: true
setup.template.overwrite: false
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0

#============================== Dashboards =====================================
# "setup.dashboards.enabled: false" now because Beats won't import dashboards
# into OpenSearch dashboards (see opensearch-project/OpenSearch-Dashboards#656
# and opensearch-project/OpenSearch-Dashboards#831). setup.template.enabled
# seems to be okay, however.
setup.dashboards.enabled: false
setup.dashboards.directory: "/usr/share/filebeat/kibana"
setup.kibana:
  host: "dashboards:5601"
  path: "/dashboards"

#================================ Logging ======================================
logging.metrics.enabled: false
