# Copyright (c) 2022 Battelle Energy Alliance, LLC.  All rights reserved.

name: "${PCAP_NODE_NAME:malcolm}"

logging.metrics.enabled: false

#================================ Modules and Processors =======================

#-------------------------- NGINX access and error logs ------------------------
filebeat.modules:
- module: nginx
  access:
    enabled: true
    var.paths: ["${FILEBEAT_NGINX_LOG_PATH:/data/nginx}/access.log*"]
  error:
    enabled: true
    var.paths: ["${FILEBEAT_NGINX_LOG_PATH:/data/nginx}/error.log*"]

processors:
  - add_tags:
      tags: [_malcolm_beats]

#================================ Outputs ======================================

#-------------------------- Logstash Output ------------------------------------
output.logstash:
  hosts: ["logstash:5044"]
  ssl.enabled: ${BEATS_SSL:false}
  ssl.certificate_authorities: ["/certs/ca.crt"]
  ssl.certificate: "/certs/client.crt"
  ssl.key: "/certs/client.key"
  ssl.supported_protocols: "TLSv1.2"
  ssl.verification_mode: "none"
